export const reg = [
    {
      id: "1293",
      fecha_recepcion: "00-00-000",
      fecha_entrega: "00-00-000",
      hostname: "Test",
      ip: "0.0.0.0",
      area: "boitc",
      proyecto: "proy01",
      alertas: "..",
      puerto: "000",
      estado: "RESUELTO",
      observacion_estado: "ninguna",
      observacion_informe: "ninguna",
    },
    {
        id: "203",
        fecha_recepcion: "00-00-000",
        fecha_entrega: "00-00-000",
        hostname: "Test",
        ip: "0.0.0.0",
        area: "boitc",
        proyecto: "proy01",
        alertas: "..",
        puerto: "000",
        estado: "RESUELTO",
        observacion_estado: "ninguna",
        observacion_informe: "ninguna",
      },
      {
        id: "23593",
        fecha_recepcion: "00-00-000",
        fecha_entrega: "00-00-000",
        hostname: "Test",
        ip: "0.0.0.0",
        area: "boitc",
        proyecto: "proy01",
        alertas: "..",
        puerto: "000",
        estado: "RESUELTO",
        observacion_estado: "ninguna",
        observacion_informe: "ninguna",
      },
      {
        id: "20287",
        fecha_recepcion: "00-00-000",
        fecha_entrega: "00-00-000",
        hostname: "Test",
        ip: "0.0.0.0",
        area: "boitc",
        proyecto: "proy01",
        alertas: "..",
        puerto: "000",
        estado: "RESUELTO",
        observacion_estado: "ninguna",
        observacion_informe: "ninguna",
      },
      {
        id: "201564",
        fecha_recepcion: "00-00-000",
        fecha_entrega: "00-00-000",
        hostname: "Test",
        ip: "0.0.0.0",
        area: "boitc",
        proyecto: "proy01",
        alertas: "..",
        puerto: "000",
        estado: "RESUELTO",
        observacion_estado: "ninguna",
        observacion_informe: "ninguna",
      },
      {
        id: "20293",
        fecha_recepcion: "00-00-000",
        fecha_entrega: "00-00-000",
        hostname: "Test",
        ip: "0.0.0.0",
        area: "boitc",
        proyecto: "proy01",
        alertas: "..",
        puerto: "000",
        estado: "RESUELTO",
        observacion_estado: "ninguna",
        observacion_informe: "ninguna",
      },
      {
        id: "20282",
        fecha_recepcion: "00-00-000",
        fecha_entrega: "00-00-000",
        hostname: "Test",
        ip: "0.0.0.0",
        area: "boitc",
        proyecto: "proy01",
        alertas: "..",
        puerto: "000",
        estado: "RESUELTO",
        observacion_estado: "ninguna",
        observacion_informe: "ninguna",
      },
  ];